name: Build
on:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
      - run: npm ci
      - name: Build          
      - run: npm run all